version: '3'
services:
  node:
    container_name: lab6_app
    restart: always
    build: .
    ports:
      - '3001:3001'
    networks:
      - lab6-app
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - lab6-app
    volumes:
      - mongodb:/data/db
networks:
  lab6-app:
    driver: bridge
volumes:
  mongodb:
    driver: local
